### ISSUE TITLE
Dataset?

### ISSUE THREAD

**Issue by ch-shin** [moqingyan/dsr-lm#2]
Thank you for the great work!

I was wondering if the dataset used in the paper can be shared or instructions to build them can be given in more detail --- I know your paper includes it and I tried it, but not sure I did it correctly. Thank you for your help!

**Comment by zhxieml** [comment]
> Thank you for the great work!
> 
> I was wondering if the dataset used in the paper can be shared or instructions to build them can be given in more detail --- I know your paper includes it and I tried it, but not sure I did it correctly. Thank you for your help!

It seems like both [CLUTRR](https://github.com/facebookresearch/clutrr) and [DBpedia-INF](https://github.com/MhmdSaiid/RuleBert) are publicly available.

**Comment by ch-shin** [comment]
> > Thank you for the great work!
> > I was wondering if the dataset used in the paper can be shared or instructions to build them can be given in more detail --- I know your paper includes it and I tried it, but not sure I did it correctly. Thank you for your help!
> 
> It seems like both [CLUTRR](https://github.com/facebookresearch/clutrr) and [DBpedia-INF](https://github.com/MhmdSaiid/RuleBert) are publicly available.

Thank you! I appreciate it!
